# Generated by Django 4.0.4 on 2022-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('mi', models.CharField(blank=True, max_length=1, null=-1)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=-1)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('driverid', models.CharField(max_length=6)),
                ('licensenumber', models.CharField(max_length=20)),
                ('licensestate', models.CharField(max_length=50)),
                ('carrier', models.CharField(max_length=50)),
                ('primaryruleset', models.CharField(max_length=50)),
                ('secondaryruleset', models.CharField(blank=True, max_length=50, null=-1)),
                ('autoapply', models.CharField(max_length=50)),
                ('allowpc', models.CharField(max_length=3)),
                ('allowym', models.CharField(max_length=3)),
                ('accttype', models.CharField(max_length=1)),
                ('updatedby', models.CharField(max_length=50)),
                ('hiredate', models.DateField()),
                ('senirotydate', models.DateField()),
                ('dob', models.DateField()),
                ('rate', models.CharField(max_length=6)),
                ('shift', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=6)),
                ('kind', models.CharField(max_length=6)),
                ('ss', models.CharField(max_length=5)),
                ('companycode', models.CharField(max_length=6)),
                ('division', models.CharField(max_length=3)),
                ('domicilecode', models.CharField(max_length=3)),
                ('fleet', models.CharField(max_length=6)),
                ('teamlead', models.CharField(max_length=3)),
                ('terminalcode', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=3)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
